[package]
name = "darkbio-cobs"
version = "0.1.2"
authors = ["Péter Szilágyi <peter@dark.bio>"]
description = "Fast COBS encoder and decoder"
repository = "https://github.com/dark-bio/cobs-rs"
documentation = "https://docs.rs/darkbio-cobs"
categories = ["encoding"]
keywords = ["cobs"]
license = "BSD-3-Clause"
edition = "2024"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dependencies]
memchr = "2"
thiserror = "2"

[dev-dependencies]
cobs = "0.5"
rand = "0.10"
sysinfo = "0.39"

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
criterion = "0.8"

[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dev-dependencies]
getrandom = { version = "0.4", features = ["wasm_js"] }

[lib]
bench = false

[[bench]]
name = "main"
harness = false
